new Text: g_ScoreboardBoxTD[2];
new Text: g_ScoreboardRowTD[2];
new Text: g_ScoreboardTeamTD[2];
new Text: g_ScoreboardColumnTD[4];
new Text: g_ScoreboardPlayerTD[2][MAX_TEAM_PLAYERS];
new Text: g_ScoreboardBombTD[2][MAX_TEAM_PLAYERS];
new Text: g_ScoreboardHealthTD[2][MAX_TEAM_PLAYERS];
new Text: g_ScoreboardScoreTD[2][MAX_TEAM_PLAYERS];
new Text: g_ScoreboardDamageTD[2][MAX_TEAM_PLAYERS];
new Text: g_ScoreboardAccuracyTD[2][MAX_TEAM_PLAYERS];
new PlayerText: g_pScoreboardResultTD[MAX_PLAYERS] = { PlayerText: INVALID_TEXT_DRAW, ... };
